---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-app
    spec:
      containers:
      - name: java
        image: 637423293208.dkr.ecr.us-east-1.amazonaws.com/ar-automation-repo:68 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: java-app